#!/usr/bin/env python3
"""Regenerates daily-diary/diary-data.js from all current/ + archived/*/ markdown files.
Run this after any write to a diary .md file so the in-game diary book stays in sync."""
import json
import os
import glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def main():
    entries = []
    for path in sorted(glob.glob(os.path.join(SCRIPT_DIR, "current", "*.md"))) + \
                sorted(glob.glob(os.path.join(SCRIPT_DIR, "archived", "*", "*.md"))):
        fname = os.path.basename(path)
        if not fname[:4].isdigit() or len(fname) < 10:
            continue
        date = fname.replace(".md", "")
        with open(path, encoding="utf-8") as f:
            content = f.read()
        entries.append((date, content))

    entries.sort(key=lambda e: e[0], reverse=True)

    lines = [
        "// ════════════════════════════════════════════════════════",
        "// DIARY DATA — auto-synced from daily-diary/ (current + archived)",
        "// Regenerated by daily-diary/regenerate-diary-data.py — do not hand-edit.",
        "// ════════════════════════════════════════════════════════",
        "",
        "const DIARY_DATA = [",
    ]
    for date, content in entries:
        lines.append("  { date:" + json.dumps(date) + ", content:" + json.dumps(content) + " },")
    lines.append("];")
    lines.append("")

    out_path = os.path.join(SCRIPT_DIR, "diary-data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {len(entries)} entries to {out_path}")


if __name__ == "__main__":
    main()
