#!/usr/bin/env python3
"""Regenerates daily-diary/diary-data.js and diary-index.json from all
current/ + archived/*/ markdown files.
Run this after any write to a diary .md file so the in-game diary book stays in sync."""
import json
import os
import glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def collect_entries():
    entries = []
    for path in sorted(glob.glob(os.path.join(SCRIPT_DIR, "current", "*.md"))) + \
                sorted(glob.glob(os.path.join(SCRIPT_DIR, "archived", "*", "*.md"))):
        fname = os.path.basename(path)
        if not fname[:4].isdigit() or len(fname) < 10:
            continue
        date = fname.replace(".md", "")
        # store path relative to SCRIPT_DIR so the browser can fetch it
        rel = os.path.relpath(path, SCRIPT_DIR).replace("\\", "/")
        with open(path, encoding="utf-8") as f:
            content = f.read()
        entries.append((date, rel, content))
    entries.sort(key=lambda e: e[0], reverse=True)
    return entries


def main():
    entries = collect_entries()

    # ── diary-data.js (legacy fallback) ──────────────────────────────
    lines = [
        "// ════════════════════════════════════════════════════════",
        "// DIARY DATA — auto-synced from daily-diary/ (current + archived)",
        "// Regenerated by daily-diary/regenerate-diary-data.py — do not hand-edit.",
        "// ════════════════════════════════════════════════════════",
        "",
        "const DIARY_DATA = [",
    ]
    for date, _rel, content in entries:
        lines.append("  { date:" + json.dumps(date) + ", content:" + json.dumps(content) + " },")
    lines.append("];")
    lines.append("")

    out_js = os.path.join(SCRIPT_DIR, "diary-data.js")
    with open(out_js, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # ── diary-index.json (used by the dashboard for live fetching) ───
    index = [{"date": date, "path": rel} for date, rel, _ in entries]
    out_idx = os.path.join(SCRIPT_DIR, "diary-index.json")
    with open(out_idx, "w", encoding="utf-8") as f:
        json.dump(index, f, ensure_ascii=False, indent=2)

    print(f"wrote {len(entries)} entries → {out_js}  +  {out_idx}")


if __name__ == "__main__":
    main()
